"""Writes CMS/Data.lean: the test messages as Lean data, so Lean's kernel can check them.

    python3 scripts/embed.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
FILES = [
    ("attached", "test/pki/attached.der", "A message signed by the test signer, with the content inside and signed attributes"),
    ("detached", "test/pki/detached.der", "The same message, signed detached: the content is not in it"),
    ("noattr", "test/pki/noattr.der", "Signed with no signed attributes: the signature is over the content itself"),
    ("msg", "test/pki/msg.txt", "The content the three messages sign"),
    ("findings", "test/real/findings-token.der", "DigiCert's timestamp token for the SHA-256 of the sealed findings file in keithadler/lean-pkcs7cms-disclosure"),
    ("digicert", "test/real/digicert-token.der", "An RFC 3161 timestamp token from DigiCert's public timestamp server for the SHA-256 of `msg`"),
]

out = ["import X509.Data", "", "/-! Generated by `scripts/embed.py` from the files in `test/`. Do not edit. -/", "",
       "namespace CMS.Data", ""]
for name, path, doc in FILES:
    data = (ROOT / path).read_bytes()
    out.append(f"/-- {doc}: {len(data)} bytes. -/")
    out.append(f"def {name}Hex : Nat := 0x{data.hex()}")
    out.append(f"def {name} : List Nat := X509.Data.bytesOf {name}Hex {len(data)} []")
    out.append("")
out.append("end CMS.Data")
(ROOT / "CMS" / "Data.lean").write_text("\n".join(out) + "\n")
print("wrote CMS/Data.lean")
